export const dataProducts = [
  {
    id: 1,
    img: "https://raw.githubusercontent.com/shaghayegh-b/bazrafkan-store/refs/heads/main/src/assets/imag/daman.jpeg",
    title: "دامن ملودی",
    code: "der",
    jens: "لینن",
    size: "مناسب سایز 36 الی 46",
    remaining: "اتمام موجودی",
    score: "3",
    price: 400000,
    dressLength: 95,
  },

  {
    id: 2,
    img: "https://raw.githubusercontent.com/shaghayegh-b/bazrafkan-store/refs/heads/main/src/assets/imag/shirt.jpeg",
    title: "تیشرت بیسیک",
    code: "ssl",
    jens: "پنبه",
    size: "مناسب سایز 36 الی 46",
    remaining: "تنها 3 عدد در انبار باقی مانده",
    score: "3",
    price: 400000,
    shoulder: "40",
    chest: "130",
    arm: "25",
    wrist: "48",
    stans: "35",
    dressLength: "85",
  },
  {
    id: 3,
    img: "https://raw.githubusercontent.com/shaghayegh-b/bazrafkan-store/refs/heads/main/src/assets/imag/tap.jpg",
    title: "تاپ یقه گرد",
    code: "af5",
    jens: "نخی",
    size: "مناسب سایز 36 الی 42",
    remaining: "تنها 1 عدد در انبار باقی مانده",
    score: "5",
    price: 170000,
    shoulder:"30",
    chest: "90 کشسانی دارد تا 110",
    dressLength: "36",
  },
  {
    id: 4,
    img: "https://raw.githubusercontent.com/shaghayegh-b/bazrafkan-store/refs/heads/main/src/assets/imag/rah.jpeg",
    title: "تونیک راه راه",
    code: "qr4",
    jens: "نخی",
    dokme: "با دکمه",
    size: "مناسب سایز 36 الی 46",
    remaining: "تنها 3 عدد در انبار باقی مانده",
    score: "3.5",
    price: 500000,
    shoulder: "45",
    chest: "115",
    arm: "35",
    wrist: "35",
    stans: "85",
    dressLength: "85",
  },
  {
    id: 5,
    img: "https://raw.githubusercontent.com/shaghayegh-b/bazrafkan-store/refs/heads/main/src/assets/imag/otsh.jpg",
    title: "کت و شلوار صوفیا",
    code: "f14",
    jens: "مازراتی",
    size: "مناسب سایز 36 الی 46",
    remaining: "تنها 2 عدد در انبار باقی مانده",
    score: "4.3",
    price: 900000,
    shoulder: "",
    chest: "",
    arm: "",
    wrist: "",
    stans: "",
    dressLength: "",
    pantsLength: "",
  },

  {
    id: 6,
    img: "https://raw.githubusercontent.com/shaghayegh-b/bazrafkan-store/refs/heads/main/src/assets/imag/jin.jpeg",
    title: "شلوار جین  بگ",
    code: "qqw",
    jens: "جین",
    dokme: "با دکمه و زیپ",
    size: "مناسب سایز 36 الی 42",
    remaining: "اتمام موجودی",
    score: "4.4",
    price: 900000,
    dressLength: "105",
  },
];
